name: Scrape Listings and Push to Anvil
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Scrape & Push
        env:
          ANVIL_INGEST_URL: ${{ secrets.ANVIL_INGEST_URL }}
          INGEST_SECRET: ${{ secrets.INGEST_SECRET }}
          ANVIL_PRESETS_URL: ${{ secrets.ANVIL_PRESETS_URL }}  # optional
        run: python scrape_and_push.py
